[build]
    publish = "public"  # Carpeta donde se encuentran los archivos estáticos generados
    command = "drush tome:static"  # Comando para generar los archivos estáticos

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
